server:
  port: 2345
  servlet:
    encoding:
      force-response: true

spring:
  profiles:
    active: @spring.profiles.active@
  config:
    import:
      - application-base.yml
      - application-datasource.yml
      - application-@spring.profiles.active@.yml
