server:
  port: 2345
  servlet:
    encoding:
      force-response: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:2345/generic
    username: user
    password: "pass"
    driverClassName: org.postgresql.Driver
    hikari:
      poolName: Hikari
      auto-commit: false
      minimumIdle: 2
      maximumPoolSize: 10
      datasource-properties:
        includeSynonyms: false
  jpa:
    database: generic
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        synonyms: false
        format_sql: true
    show-sql: true

# docker pull postgres:14.4-alpine
# docker run -d --name generic -e POSTGRES_PASSWORD=user -e POSTGRES_USER=pass -e POSTGRES_DB=generic -p 2345:2345 postgres:14.4-alpine
# docker ps
# docker exec -it generic psql -U user -d generic