server:
  port: 2345
  name: false
  standalone-war: false
  servlet:
    encoding:
      force-response: true

spring:
  config:
    activate:
      on-profile: @spring.profiles.active@
    import:
      - application-base.yaml
      - application-datasource.yaml
      - application-@spring.profiles.active@.yaml
